#!/bin/bash

# Regression coverage for PM2 launch commands generated by env_start.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
TEST_ROOT="$(mktemp -d)"
trap 'rm -rf "$TEST_ROOT"' EXIT

export HOME="$TEST_ROOT/home"
export SHIPGLOWS_STATE_DIR="$HOME/.shipglows"
export SHIPGLOWS_STATE_DIR="$SHIPGLOWS_STATE_DIR"
export SHIPGLOWS_PROJECTS_DIR="$HOME/projects"
export SHIPGLOWS_PROJECTS_DIR="$SHIPGLOWS_PROJECTS_DIR"
export SHIPGLOWS_ERROR_TRAPS=false
export SHIPGLOWS_STRICT_MODE=false
export SHIPGLOWS_LOGGING_ENABLED=false
export SHIPGLOWS_LOGGING_ENABLED=false

source "$REPO_ROOT/cli/lib.sh"
trap - ERR 2>/dev/null || true

fail() {
    printf 'FAIL: %s\n' "$1" >&2
    exit 1
}

assert_eq() {
    [ "$1" = "$2" ] || fail "$3 (expected '$1', got '$2')"
}

# Keep this regression focused on ecosystem generation; PM2 lifecycle and
# discovery behavior are covered by their dedicated test suites.
validate_project_path() { return 0; }
resolve_project_path_into() { printf -v "$1" '%s' "$2"; }
derive_pm2_app_name() { printf 'runtime-app\n'; }
detect_project_type() { printf 'python:fastapi\n'; }
detect_dev_command() { printf './venv/bin/python main.py\n'; }
find_available_port() { printf '3000\n'; }
invalidate_pm2_cache() { :; }
invalidate_after_pm2_mutation() { :; }
invalidate_home_folders_cache() { :; }
pm2_app_data_load() { printf -v "$1" '%s' ''; }
pm2_data_load() { printf -v "$1" '%s' ''; }
pm2_status_load() { printf -v "$1" '%s' 'online'; }
refresh_user_caddy_from_pm2() { :; }
registry_update() { :; }
fuser() { :; }
pm2() {
    case "${1:-}" in
        jlist) printf '[]\n' ;;
        *) return 0 ;;
    esac
}

project_dir="$TEST_ROOT/python-app"
mkdir -p "$project_dir/.flox" "$project_dir/venv/bin"
: > "$project_dir/venv/bin/python"
cat > "$project_dir/.shipglows.env" <<'EOF'
# Project runtime settings: data only, never executed by ShipGlows.
SHIPGLOWS_ENV_PORT=41000
SHIPGLOWS_AUTO_REPAIR=false
EOF

should_enable_doppler() { return 1; }
env_start "$project_dir" >/dev/null
runtime_args="$(node -e "const app = require(process.argv[1]).apps[0]; process.stdout.write(app.args[1]);" "$project_dir/ecosystem.config.cjs")"
printf '%s' "$runtime_args" | grep -Fq 'export PORT=41000 && flox activate -- bash -lc' \
    || fail "project runtime settings pin the generated PM2 port"
printf '%s' "$runtime_args" | grep -Fq './venv/bin/python main.py' \
    || fail "non-Expo runtime preserves the detected command"
! printf '%s' "$runtime_args" | grep -Fq "'\"'\"'" \
    || fail "non-Expo runtime does not re-escape the command passed to bash -lc"
project_runtime_settings_load "$project_dir" test_port test_auto_repair
assert_eq "$test_port" "41000" "project runtime settings expose the requested port"
assert_eq "$test_auto_repair" "false" "project runtime settings can disable auto-repair"

cat > "$project_dir/.shipglows.env" <<'EOF'
SHIPGLOWS_AUTO_REPAIRS=false
EOF
if project_runtime_settings_load "$project_dir" test_port test_auto_repair >/dev/null 2>&1; then
    fail "unknown project runtime settings must fail instead of silently using defaults"
fi

cat > "$project_dir/.shipglows.env" <<'EOF'
# Project runtime settings: data only, never executed by ShipGlows.
SHIPGLOWS_ENV_PORT=41000
SHIPGLOWS_AUTO_REPAIR=false
EOF

SHIPGLOWS_ENV_PORT=45000
env_start "$project_dir" >/dev/null
runtime_args="$(node -e "const app = require(process.argv[1]).apps[0]; process.stdout.write(app.args[1]);" "$project_dir/ecosystem.config.cjs")"
printf '%s' "$runtime_args" | grep -Fq 'export PORT=45000 && flox activate -- bash -lc' \
    || fail "an explicit environment port overrides the persisted PM2 port"
unset SHIPGLOWS_ENV_PORT

rm -f "$project_dir/ecosystem.config.cjs" "$project_dir/.shipglows.env"
should_enable_doppler() { return 0; }
doppler() {
    if [ "${1:-}" = "run" ] && [ "${3:-}" = "echo" ]; then
        printf 'doppler_ok\n'
    fi
}
env_start "$project_dir" >/dev/null
runtime_args="$(node -e "const app = require(process.argv[1]).apps[0]; process.stdout.write(app.args[1]);" "$project_dir/ecosystem.config.cjs")"
case "$runtime_args" in
    "doppler run -- bash -lc "*) ;;
    *) fail "Doppler remains the outer runtime wrapper ($runtime_args)" ;;
esac
printf '%s' "$runtime_args" | grep -Fq 'export PORT=3000 && flox activate -- bash -lc' \
    || fail "Doppler launch preserves the Flox runtime command"

project_runtime_settings_load "$project_dir" test_port test_auto_repair
assert_eq "$test_auto_repair" "true" "auto-repair defaults to enabled when no project settings file exists"

cat > "$project_dir/.shipglows.env" <<'EOF'
SHIPGLOWS_AUTO_REPAIR=false
EOF
restart_status_calls=0
pm2_status_load() {
    restart_status_calls=$((restart_status_calls + 1))
    if [ "$restart_status_calls" -eq 1 ]; then
        printf -v "$1" '%s' 'online'
    else
        printf -v "$1" '%s' 'errored'
    fi
}
env_start_calls=0
env_start() {
    env_start_calls=$((env_start_calls + 1))
    return 0
}
offer_codex_environment_repair() { return 0; }
SHIPGLOWS_RESTART_VERIFY_SECS=1
if env_restart "$project_dir"; then
    fail "restart must report the failed PM2 restart when auto-repair is disabled"
fi
assert_eq "$env_start_calls" "0" "disabled auto-repair never regenerates the runtime"

echo "Flox runtime launch regressions passed"
