#!/usr/bin/env bash

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
MODULE="$ROOT/cli/windows/ShipGlows.DevServer.psm1"
ENTRYPOINT="$ROOT/cli/windows/shipglows-devserver.ps1"
INSTALLER="$ROOT/cli/windows/install-devserver.ps1"
BOOTSTRAP="$ROOT/install-shipglows.ps1"

for file in "$MODULE" "$ENTRYPOINT" "$INSTALLER" "$BOOTSTRAP"; do
  test -f "$file"
done

! rg -n 'Invoke-Expression|GetRelativePath|Read-SgRegistry \\$Config \.projects' "$MODULE" "$ENTRYPOINT" "$INSTALLER"
! rg -n '"[^"\n]*\$[A-Za-z_][A-Za-z0-9_]*:' "$MODULE" "$ENTRYPOINT" "$INSTALLER"
! rg -n 'New-Item[^\n]*-LiteralPath' "$MODULE" "$ENTRYPOINT" "$INSTALLER"
rg -n 'Import-Module .*DisableNameChecking' "$ENTRYPOINT"
rg -n 'Export-ModuleMember -Function .*Write-SgInfo,Write-SgWarn,Write-SgError' "$MODULE"
rg -n "gumVersion = '0\.17\.0'|gumSha256 = 'B2BE80531C6BABC8D4E0E6CA95773D58118A2E1582AE006AACE08DBC55503072'" "$INSTALLER"
rg -n 'Get-FileHash .*SHA256|github\.com/charmbracelet/gum/releases/download' "$INSTALLER"
rg -n 'gum_\$\{gumVersion\}_Windows_x86_64/gum\.exe' "$INSTALLER"
rg -n 'Get-SgGumCommand|Get-SgFzfCommand|gum choose|Read-SgChoice' "$ENTRYPOINT"
rg -n 'choiceUiAvailable|fzf.*--height=~60%.*--layout=reverse.*--border|Prefer it over Gum' "$ENTRYPOINT"
rg -n 'newline-delimited stdin|\$lines -join \[Environment\]::NewLine.*\| & \$gum choose|replace .\[\\r\\n\]\+' "$ENTRYPOINT"
rg -n -- "--item\.foreground.*255|--item\.background.*0|--cursor\.foreground.*0|--cursor\.background.*212|--selected\.foreground.*0|--selected\.background.*212" "$ENTRYPOINT"
rg -n 'ValueFromRemainingArguments|Resolve-SgAction|Show-SgShortcutHelp' "$ENTRYPOINT"
rg -n "'m n' = 'navigate'|'m r' = 'select-restart'|'m t' = 'select-stop'|'m o' = 'stop-all'|'m l' = 'select-logs'|'e'   = 'select-start'" "$ENTRYPOINT"
rg -n "'u'   = 'update'|'update' \{ Invoke-SgUpdate \}|s u      Update ShipGlows" "$ENTRYPOINT"
rg -n 'raw\.githubusercontent\.com/commandglows/shipglows/main/install-shipglows\.ps1|Parser.*ParseFile|InstallMode full -ShipglowsDir|shipglows-update-' "$ENTRYPOINT"
rg -n "'select-start'|'select-stop'|'select-restart'|'select-logs'" "$ENTRYPOINT"
rg -n "Unknown Windows shortcut path:.*Run 's h'|exit 2" "$ENTRYPOINT"
rg -n 'Push-Location -LiteralPath \$entry\.path|NoProfile -ExecutionPolicy Bypass -NoExit|Type exit to return' "$ENTRYPOINT"
! rg -n 'Invoke-Expression|-Command.*Set-Location' "$ENTRYPOINT"
rg -n "Install-SgWingetPackage 'git\.exe' 'Git\.Git'|Install-SgWingetPackage 'gh\.exe' 'GitHub\.cli'" "$INSTALLER"
rg -n "Install-SgWingetPackage 'fzf\.exe' 'junegunn\.fzf'|@\('gum','fzf','git','gh','node','npm','pnpm','uv','flutter'\)" "$INSTALLER"
rg -n "Install-SgWingetPackage 'node\.exe' 'OpenJS\.NodeJS\.LTS'|Install-SgWingetPackage 'uv\.exe' 'astral-sh\.uv'" "$INSTALLER"
rg -n 'Install-SgPnpm|npm install --global corepack@latest|corepack enable pnpm|npm install --global pnpm@latest' "$INSTALLER"
rg -n 'Initialize-SgPnpmGlobalBin|config get global-bin-dir|LOCALAPPDATA.*pnpm\\bin|Add-SgUserPathEntry.*globalBin' "$INSTALLER"
rg -n "Test-SgToolRuns 'pnpm\.cmd'|pnpm --version check failed" "$INSTALLER"
pnpm_path_line="$(rg -n 'Add-SgUserPathEntry \$defaultGlobalBin' "$INSTALLER" | head -1 | cut -d: -f1)"
pnpm_config_line="$(rg -n 'config get global-bin-dir' "$INSTALLER" | head -1 | cut -d: -f1)"
test -n "$pnpm_path_line" && test -n "$pnpm_config_line" && test "$pnpm_path_line" -lt "$pnpm_config_line"
rg -n 'Install-SgFlutter|Install Flutter Web SDK now\? \[y/N\]|git clone --depth 1 --branch stable https://github\.com/flutter/flutter\.git|config --enable-web' "$INSTALLER"
rg -n 'Install-SgOptionalAgent|Optional coding agents|Each agent is a separate choice|Install Codex CLI now\? \[y/N\]' "$INSTALLER"
rg -n 'Resolve-SgCodexPermissionMode|Set-SgCodexPermissionMode|Codex permissions|Workspace access \(recommended\)|Full access: no sandbox|SHIPGLOWS_CODEX_PERMISSION_MODE' "$INSTALLER"
rg -n "approvalPolicy.*'never'.*'on-request'|permissionProfile.*':danger-full-access'.*':workspace'" "$INSTALLER"
rg -n 'shipglows codex autonomous|approval_policy|default_permissions|sandbox_mode|shipglows-backup-' "$INSTALLER"
rg -n "'@openai/codex'|'@anthropic-ai/claude-code'|'opencode-ai'|'@kilocode/cli'" "$INSTALLER"
rg -n 'Authentication happens when you first run|never asks for or stores credentials|pnpm could not make .* npm fallback' "$INSTALLER"
rg -n 'AllowInstallScripts|--allow-scripts=\$PackageName' "$INSTALLER"
rg -n 'Test-SgToolRuns \$CommandName \$KnownPaths|version check failed' "$INSTALLER"
rg -n '\[Console\]::IsInputRedirected|non-interactive installation' "$INSTALLER"
rg -n 'keep this window open|WinGet can take several minutes|\| Out-Host' "$INSTALLER"
rg -n 'function Write-SgInstallerWarning|WARNING:.*ForegroundColor Yellow|--disable-interactivity.*\| Out-Null' "$INSTALLER"
! rg -n 'Write-Warning|winget\.Source install.*\| Out-Host' "$INSTALLER"
rg -n 'Install-SgCommandWrappers|Add-SgRuntimeToUserPath|shipglows-dev\.cmd|s\.cmd|Short command installed: s' "$INSTALLER"
rg -n 'Install-SgApplicationCommandWrapper|@call "\$target" %\*|Application command installed:' "$INSTALLER"
rg -n "Install-SgApplicationCommandWrapper '(npm|npx|corepack|pnpm|codex|claude|opencode|kilocode)'" "$INSTALLER"
rg -n 'Install-SgAgentShortcut|%~dp0\$TargetName\.cmd|Agent shortcut installed:' "$INSTALLER"
rg -n "Install-SgAgentShortcut 'c' 'claude'|Install-SgAgentShortcut 'co' 'codex'|Install-SgAgentShortcut 'cor' 'codex' @\('resume'\)|Install-SgAgentShortcut 'oc' 'opencode'|Install-SgAgentShortcut 'kc' 'kilocode'" "$INSTALLER"
rg -n 'Install-SgShellShortcut|Shell shortcut installed:' "$INSTALLER"
rg -n "Install-SgShellShortcut 're'.*ExecutionPolicy Bypass|Install-SgShellShortcut 'ch'.*Clear-History.*Get-PSReadLineOption.*HistorySavePath.*Clear-Host" "$INSTALLER"
rg -n "short command.*already used|ShipGlows did not replace it" "$INSTALLER"
rg -n 'Disable-SgBlockedPowerShellShim|ChangeExtension\(\$cmdPath, .ps1.\)|shipglows-disabled|Move-Item -LiteralPath \$ps1Path' "$INSTALLER"
rg -n 'userRoot.*USERPROFILE|StartsWith\(\$userRoot.*OrdinalIgnoreCase|Protected system PowerShell shim left unchanged' "$INSTALLER"
rg -n "Disable-SgBlockedPowerShellShim '(npm|npx|corepack|pnpm|codex|claude|opencode|kilocode)'" "$INSTALLER"
last_wrapper_line="$(rg -n "Install-SgApplicationCommandWrapper 'kilocode'" "$INSTALLER" | tail -1 | cut -d: -f1)"
runtime_priority_line="$(rg -n '^Add-SgRuntimeToUserPath\r?$' "$INSTALLER" | tail -1 | cut -d: -f1)"
test -n "$last_wrapper_line" && test -n "$runtime_priority_line" && test "$last_wrapper_line" -lt "$runtime_priority_line"
rg -n 'ExecutionPolicy Bypass -File "%~dp0shipglows-devserver\.ps1" %\*' "$INSTALLER"
rg -n 'Remove-SgObsoleteProfileCommand|Removed the obsolete ShipGlows profile command|ShipGlows DevServer \(managed\)' "$INSTALLER"
! rg -n 'function shipglows-dev \{ & ' "$INSTALLER"
rg -n 'gh auth login --hostname github\.com --git-protocol https --web|gh repo list --limit 200|gh repo clone' "$ENTRYPOINT"
rg -n '\$parsedRepositories = \$json \| ConvertFrom-Json|\$repositories = @\(\$parsedRepositories\)|Windows PowerShell 5\.1 preserves a JSON top-level array' "$ENTRYPOINT"
! rg -n 'gh auth token|GH_TOKEN|GITHUB_TOKEN' "$ENTRYPOINT" "$INSTALLER"
! rg -n 'WSL est disponible|Lancement de la configuration locale Windows|Utilise ensuite|Pour les projets locaux' "$BOOTSTRAP"
! rg -n "ValidateSet\\('local','full'\\)" "$BOOTSTRAP"
! rg -n 'InstallMode = \$\(if \(\$env:SHIPGLOWS_INSTALL_MODE' "$BOOTSTRAP"
rg -n '\[string\]\$InstallMode,|InstallMode must be local or full|\$InstallMode -notin @\(' "$BOOTSTRAP"
rg -n 'Select-WindowsInstallMode|Choose 1 or 2|Local DevServer \(full, recommended\)|IsInputRedirected' "$BOOTSTRAP"
rg -n "USERPROFILE '.shipglows'|FileAttributes.*Hidden|defaultHiddenRoot" "$BOOTSTRAP" "$INSTALLER"
rg -n "runtimeDir = Join-Path \$ShipglowsDir 'bin'|Remove-SgLegacyVisibleRuntime|@\('bin', 'cli', 'local'\)|legacyBin" "$INSTALLER"
legacy_cleanup_line="$(rg -n '^Remove-SgLegacyVisibleRuntime\r?$' "$INSTALLER" | tail -1 | cut -d: -f1)"
wrapper_install_line="$(rg -n '^Install-SgCommandWrappers\r?$' "$INSTALLER" | tail -1 | cut -d: -f1)"
test -n "$legacy_cleanup_line" && test -n "$wrapper_install_line" && test "$legacy_cleanup_line" -lt "$wrapper_install_line"
rg -n "USERPROFILE 'ShipGlows'" "$INSTALLER" "$MODULE"
! rg -n "Choose 1 or 2 \\[2\\]|'' \\{ return 'full' \\}" "$BOOTSTRAP"
rg -n "'' \{ Write-Warn 'A choice is required\. Enter 1, 2, or 0\.' \}" "$BOOTSTRAP"
for windows_file in 'ShipGlows\.DevServer\.psm1' 'shipglows-devserver\.ps1' 'install-devserver\.ps1'; do
  rg -n "$windows_file" "$BOOTSTRAP"
done
rg -n '\$windowsCandidates = @\(' "$BOOTSTRAP"
! rg -n '\$windowsCandidates = @\([^)]*\) \| Where-Object' "$BOOTSTRAP"
rg -n "127\\.0\\.0\\.1|registry\\.json|registry\\.lock|commandSignature|startTimeUtc" "$MODULE"
rg -n "Test-SgGitUrl|embedded credentials|Only HTTPS and SSH" "$MODULE" "$ENTRYPOINT"

echo "Windows DevServer static contract: OK"
