#!/usr/bin/env bash

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
WINDOWS_DIR="$ROOT/cli/windows"
MODULE="$ROOT/cli/windows/ShipGlows.DevServer.psm1"
RUNTIME_STATUS_MODULE="$ROOT/cli/windows/ShipGlows.RuntimeStatus.psm1"
FLUTTER_SUPERVISOR="$ROOT/cli/windows/ShipGlows.FlutterSupervisor.ps1"
CATALOG_REFRESHER="$ROOT/cli/windows/ShipGlows.ProjectCatalogRefresh.ps1"
ENTRYPOINT="$ROOT/cli/windows/shipglows-devserver.ps1"
INSTALLER="$ROOT/cli/windows/install-devserver.ps1"
BOOTSTRAP="$ROOT/install-shipglows.ps1"
CODEX_MCP_MODULE="$ROOT/cli/windows/ShipGlows.CodexMcp.psm1"
MOBILE_MODULE="$ROOT/cli/windows/ShipGlows.MobileToolchain.psm1"
INSTALLER_ENGINE_MODULE="$ROOT/cli/windows/ShipGlows.InstallerEngine.psm1"
INSTALLER_CONSOLE_MODULE="$ROOT/cli/windows/ShipGlows.InstallerConsole.psm1"
AGENT_INSTRUCTIONS_MODULE="$ROOT/cli/windows/ShipGlows.AgentInstructions.psm1"
AUTH_MODULE="$ROOT/cli/windows/ShipGlows.Auth.psm1"
WSL_TURSO_MODULE="$ROOT/cli/windows/ShipGlows.WslTurso.psm1"
TURSO_INSTALLER="$ROOT/cli/install-turso-cloud.sh"
ENVIRONMENT_CLI="$ROOT/cli/environment/shipglows_environment.py"
SHIPGLOWS_COMMAND="$ROOT/cli/windows/shipglows.ps1"
MANAGED_PWSH="$HOME/.shipglows/toolchains/powershell/7.6.5/win-x64/pwsh.exe"

if [[ ! -x "$MANAGED_PWSH" ]]; then
  export SHIPGLOWS_RUNTIME_MODULE="$WINDOWS_DIR/ShipGlows.PowerShellRuntime.psm1"
  powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command \
    '$ErrorActionPreference="Stop"; Import-Module $env:SHIPGLOWS_RUNTIME_MODULE -Force -DisableNameChecking; [void](Ensure-SgPowerShellRuntime)'
fi
test -x "$MANAGED_PWSH"
run_ps() { "$MANAGED_PWSH" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File "$@"; }

for file in "$MODULE" "$FLUTTER_SUPERVISOR" "$CATALOG_REFRESHER" "$ENTRYPOINT" "$INSTALLER" "$BOOTSTRAP" "$CODEX_MCP_MODULE" "$MOBILE_MODULE" "$INSTALLER_ENGINE_MODULE" "$INSTALLER_CONSOLE_MODULE" "$AGENT_INSTRUCTIONS_MODULE" "$AUTH_MODULE" "$WSL_TURSO_MODULE" "$TURSO_INSTALLER" "$ENVIRONMENT_CLI" "$SHIPGLOWS_COMMAND"; do
  test -f "$file"
done

for environment_contract in executor-contract.py inferred-project-contract.py mise-backend-contract.py plan-contract.py preparation-contract.py schema-contract.py security-contract.py state-contract.py version-contract.py windows-tauri-backend-contract.py; do
  python "$ROOT/tests/environment/$environment_contract"
done
run_ps "$ROOT/tests/windows/environment-observation.ps1"
run_ps "$ROOT/tests/windows/environment-mise-adapter.ps1"
run_ps "$ROOT/tests/windows/environment-provider-contract.ps1"
run_ps "$ROOT/tests/windows/environment-activation-devserver-contract.ps1"
run_ps "$ROOT/tests/windows/environment-installed-runtime.ps1"
run_ps "$ROOT/tests/windows/wsl-turso.ps1"
bash "$ROOT/tests/cli/turso-cloud-installer.sh"
run_ps "$ROOT/tests/windows/runtime-update-transaction.ps1"
run_ps "$ROOT/tests/windows/runtime-status.ps1"
run_ps "$ROOT/tests/windows/update-command.ps1"
run_ps "$ROOT/tests/windows/installer-engine-ui.ps1"
run_ps "$ROOT/tests/windows/codex-playwright-mcp.ps1"
run_ps "$ROOT/tests/windows/mobile-toolchain.ps1"
run_ps "$ROOT/tests/windows/required-gate-paths.ps1"
run_ps "$ROOT/tests/windows/agent-instructions.ps1"
run_ps "$ROOT/tests/windows/auth-playwright.ps1"
run_ps "$ROOT/tests/windows/bootstrap-ref-resolution.ps1"
run_ps "$ROOT/tests/windows/install-surface-contract.ps1"
run_ps "$ROOT/tests/windows/powershell-runtime.ps1"
run_ps "$ROOT/tests/windows/rio-tab-rename.ps1"
for regression in \
  browser-extension-lab.ps1 \
  browser-extension-runtime.ps1 \
  browser-extension-project.ps1 \
  devserver-user-guidance.ps1 \
  devserver-monorepo-detection.ps1 \
  devserver-display-name.ps1 \
  devserver-port-reservation.ps1 \
  devserver-cli-performance.ps1 \
  project-environment-schema.ps1 \
  devserver-registry-migration.ps1 \
  devserver-flutter-background.ps1 \
  devserver-flutter-supervisor.ps1 \
  devserver-flutter-stop.ps1 \
  devserver-metadata-sync.ps1 \
  devserver-dependency-setup.ps1 \
  devserver-project-catalog.ps1 \
  github-clone-filter.ps1 \
  devserver-start-detach.ps1 \
  devserver-start-state.ps1 \
  devserver-stop-behavior.ps1; do
  run_ps "$ROOT/tests/windows/$regression"
done
bash "$ROOT/tests/install/playwright-mcp-contract.sh"
rg -n 'Install-SgPlaywrightChromiumForAgents|Get-SgNativeNpxPath|npm.*view.*@playwright/mcp.*version|Get-SgPlaywrightChromiumExecutable|Playwright Chromium was not proven' "$INSTALLER"
rg -n 'mcp_servers\.playwright|PlaywrightVersion|ChromiumPath|exact resolved package version|--headless.*--browser.*chromium' "$CODEX_MCP_MODULE"
! rg -n '@playwright/mcp@latest|supabase@latest' "$INSTALLER" "$CODEX_MCP_MODULE" "$MOBILE_MODULE"
rg -n 'ShipGlows\.CodexMcp\.psm1' "$BOOTSTRAP" "$INSTALLER"
rg -n 'ShipGlows\.AgentInstructions\.psm1|Install-SgAgentEnvironmentInstructions' "$BOOTSTRAP" "$INSTALLER"
rg -n 'Get-SgWslState|Get-SgWslInstallPlan|Invoke-SgWslInstall|Get-SgTursoCloudState|Get-SgTursoCloudInstallPlan|Invoke-SgTursoCloudInstall' "$WSL_TURSO_MODULE" "$INSTALLER"
! rg -n 'turso[[:space:]]+(auth|db|shell)|releases/latest|/latest/' "$WSL_TURSO_MODULE" "$TURSO_INSTALLER"

! rg -n 'Invoke-Expression|GetRelativePath|Read-SgRegistry \\$Config \.projects' "$MODULE" "$ENTRYPOINT" "$INSTALLER"
! rg -n '"[^"\n]*\$[A-Za-z_][A-Za-z0-9_]*:' "$MODULE" "$ENTRYPOINT" "$INSTALLER"
! rg -n 'New-Item[^\n]*-LiteralPath' "$MODULE" "$ENTRYPOINT" "$INSTALLER"
rg -n 'Import-Module .*DisableNameChecking' "$ENTRYPOINT"
rg -n 'Export-ModuleMember -Function .*Write-SgInfo,Write-SgWarn,Write-SgError' "$MODULE"
rg -n "gumVersion = '0\.17\.0'|gumSha256 = 'B2BE80531C6BABC8D4E0E6CA95773D58118A2E1582AE006AACE08DBC55503072'" "$INSTALLER"
rg -n 'Get-FileHash .*SHA256|github\.com/charmbracelet/gum/releases/download' "$INSTALLER"
rg -n 'gum_\$\{gumVersion\}_Windows_x86_64/gum\.exe' "$INSTALLER"
rg -n 'Get-SgGumCommand|Get-SgFzfCommand|gum choose|Read-SgChoice' "$ENTRYPOINT"
rg -n 'choiceUiAvailable|fzf.*--height=~60%.*--layout=reverse.*--border|Prefer it over Gum' "$ENTRYPOINT"
rg -n 'newline-delimited stdin|\$lines -join \[Environment\]::NewLine.*\| & \$gum choose|replace .\[\\r\\n\]\+' "$ENTRYPOINT"
rg -n -- "--item\.foreground.*255|--item\.background.*0|--cursor\.foreground.*0|--cursor\.background.*212|--selected\.foreground.*0|--selected\.background.*212" "$ENTRYPOINT"
rg -n 'ValueFromRemainingArguments|Resolve-SgAction|Show-SgShortcutHelp' "$ENTRYPOINT"
rg -n "'m n' = 'navigate'|'m r' = 'select-restart'|'m t' = 'select-stop'|'m o' = 'stop-all'|'m l' = 'select-logs'|'e'   = 'select-start'" "$ENTRYPOINT"
rg -n "'u'   = 'update'|'update' \{ Invoke-SgUpdate \}|s u      Update ShipGlows" "$ENTRYPOINT"
rg -n 'raw\.githubusercontent\.com/commandglows/shipglows/main/install-shipglows\.ps1|Parser.*ParseFile|InstallMode full -ShipglowsDir|shipglows-update-' "$ENTRYPOINT"
rg -n "'select-start'|'select-stop'|'select-restart'|'select-logs'" "$ENTRYPOINT"
rg -n "'unregister'|'select-unregister'|'m w' = 'select-unregister'|files are preserved" "$ENTRYPOINT"
rg -n "Unknown Windows shortcut path:.*Run 's h'|exit 2" "$ENTRYPOINT"
rg -n 'Push-Location -LiteralPath \$entry\.path|SHIPGLOWS_MANAGED_PWSH|NoProfile -ExecutionPolicy Bypass -NoExit|Type exit to return' "$ENTRYPOINT"
! rg -n 'Invoke-Expression|-Command.*Set-Location' "$ENTRYPOINT"
rg -n "Install-SgWingetPackage 'git\.exe' 'Git\.Git'|Install-SgWingetPackage 'gh\.exe' 'GitHub\.cli'" "$INSTALLER"
rg -n "Install-SgWingetPackage 'fzf\.exe' 'junegunn\.fzf'|@\('gum','fzf','git','gh','node','npm','pnpm','uv','flutter'\)" "$INSTALLER"
rg -n "Install-SgWingetPackage 'node\.exe' 'OpenJS\.NodeJS\.LTS'|Install-SgWingetPackage 'uv\.exe' 'astral-sh\.uv'" "$INSTALLER"
rg -n 'Install-SgPnpm|Installing Corepack|Enabling pnpm with Corepack|Installing pnpm' "$INSTALLER"
rg -n "OperationId 'tool[.]corepack'|OperationId 'tool[.]corepack-pnpm'|OperationId 'tool[.]pnpm'|Test-SgToolRuns.*Invoke-SgBoundedProcess" "$INSTALLER"
! rg -n '& \$corepack enable pnpm|& \$npm install --global (corepack|pnpm)' "$INSTALLER"
rg -n "Initialize-SgPnpmGlobalBin|@\('config','get','global-bin-dir'\)|LOCALAPPDATA.*pnpm\\\\bin|Add-SgUserPathEntry.*globalBin" "$INSTALLER"
rg -n "Test-SgToolRuns 'pnpm\.cmd'|pnpm --version check failed" "$INSTALLER"
pnpm_path_line="$(rg -n 'Add-SgUserPathEntry \$defaultGlobalBin' "$INSTALLER" | head -1 | cut -d: -f1)"
pnpm_config_line="$(rg -n "@\('config','get','global-bin-dir'\)" "$INSTALLER" | head -1 | cut -d: -f1)"
test -n "$pnpm_path_line" && test -n "$pnpm_config_line" && test "$pnpm_path_line" -lt "$pnpm_config_line"
rg -n 'Install-SgFlutter|Install-SgJdk17|Install-SgAndroidCommandLineTools|Install-SgAndroidToolchain|Install the Android emulator and create ShipGlows_API_36 now\? \[y/N\]|sdkmanager.*--licenses|Get-SgFlutterAndroidDiagnostic' "$INSTALLER"
rg -F -n 'refs/remotes/origin/shipglows-stable' "$INSTALLER"
rg -F -n "@('checkout','-B','stable'" "$INSTALLER"
rg -F -n "Schema = 'shipglows.flutter-baseline/v1'" "$INSTALLER"
rg -F -n "FlutterVersion = '3.47.1'" "$INSTALLER"
rg -F -n "Commit = '6655482ec06e547f90abf8ae7590466f4415978d'" "$INSTALLER"
rg -F -n 'Flutter stable convergence failed; restored the previous managed revision.' "$INSTALLER"
rg -F -n "SetEnvironmentVariable('CHROME_EXECUTABLE'" "$INSTALLER"
rg -F -n 'chromium_headless_shell-$revision\chrome-headless-shell-win64\chrome-headless-shell.exe' "$INSTALLER"
rg -F -n 'Test-SgChromiumExecutableResult $browserProbe $browserCheck' "$INSTALLER"
rg -F -n "EnvironmentVariables['CHROME_EXECUTABLE']" "$WINDOWS_DIR/ShipGlows.FlutterSupervisor.ps1"
! rg -n 'Install Flutter Web SDK now\? \[y/N\]|--accept.*license|yes.*android-licenses' "$INSTALLER" "$MOBILE_MODULE"
rg -n 'Get-SgAgentMcpPlan|Get-SgAgentConfigWritePlan|Write-SgNewAgentConfig|Get-SgAndroidInstallPlan|Get-SgProjectServiceNeeds|Test-SgWindowsDeveloperMode' "$INSTALLER" "$MOBILE_MODULE"
rg -n 'Get-SgProjectMcpDefinitions|Get-SgProjectAgentMcpConfigPlan|Write-SgManagedProjectConfig|agent-mcp-project-state[.]json|Add-SgProjectMcpGitExclude|ready per project' "$INSTALLER" "$MOBILE_MODULE"
rg -n -F -e '.codex\config.toml' -e '.mcp.json' -e '.gemini\settings.json' -e '.opencode\opencode.json' -e '.kilo\kilo.json' "$MOBILE_MODULE"
! rg -n 'GitHub remains the global read-only baseline|GitHub MCP is configured globally' "$ROOT/README.md" "$ROOT/shipglows_data/technical/runtime-cli.md"
rg -n 'ReplaceAgentConfigs|ReplaceExistingAgentConfigs|replace-existing|explicit maintainer install owns the complete agent MCP inventory' "$INSTALLER" "$MOBILE_MODULE" "$BOOTSTRAP"
rg -n 'Resolve-SgAgentConfigPath.*OpenCode|Resolve-SgAgentConfigPath.*Kilo|\.jsonc' "$INSTALLER" "$MOBILE_MODULE"
rg -n "mcp=.*servers|McpShape='servers'|opencode\.json|kilo\.json|Resolve-SgKiloCommand|kilo\.cmd|kilocode\.cmd" "$INSTALLER" "$MOBILE_MODULE"
rg -n 'Install-SgDetectedServiceClis|Resolve-SgNpmVersion|firebase-tools@|flutterfire_cli.*Version|supabase@.*Version|executable verification failed' "$INSTALLER"
rg -n 'Get-SgAgentInstallPlan|Install-SgMissingAgentClis|@openai/codex|@anthropic-ai/claude-code|opencode-ai|@kilocode/cli' "$INSTALLER" "$MOBILE_MODULE"
rg -n 'convex@|vercel@|firebase-tools@.*mcp|convex@.*mcp.*start' "$INSTALLER" "$MOBILE_MODULE"
rg -n 'Invoke-SgBoundedProcess|TimedOut|Stop-SgProcessTree|ToolchainReady|LicensesReady|DeviceReady' "$INSTALLER" "$MOBILE_MODULE"
rg -n 'ConvertTo-SgWindowsArgument|ConvertTo-SgCmdBatchArgument|ExpectedStartTimeUtc|StartTime.ToUniversalTime' "$MOBILE_MODULE"
! rg -n 'Start-Process.*ArgumentList' "$INSTALLER" "$MOBILE_MODULE"
rg -n 'api\.adoptium\.net|Resolve-SgAdoptiumJdkPackage|repository2-3\.xml|Resolve-SgAndroidCommandLineToolsPackage|Get-FileHash.*SHA256|ANDROID_HOME|ANDROID_SDK_ROOT' "$INSTALLER" "$MOBILE_MODULE"
rg -n -F -- '--registry=https://registry.npmjs.org/' "$INSTALLER" "$CODEX_MCP_MODULE" "$MOBILE_MODULE"
rg -n 'system-images;android-|avdmanager|create.*avd|-list-avds|-accel-check|VMMonitorModeExtensions' "$INSTALLER" "$MOBILE_MODULE"
rg -n 'ApiLevel = 36|platforms;android-36|build-tools;36\.0\.0|system-images;android-36|ShipGlows_API_36' "$MOBILE_MODULE"
rg -n 'Install-SgTauriAndroidToolchain|Get-SgTauriAndroidProjectState|Get-SgTauriAndroidHostPlan|Get-SgTauriMiseConfig|jdx\.mise|ndk;29\.0\.14206865|Open Codex in this project to perform and verify the migration' "$INSTALLER" "$MOBILE_MODULE"
rg -n 'Install-SgTauriRustWrappers|cargo.*rustc.*rustup|-C.*exec --' "$INSTALLER"
! rg -n 'tauri android init|tauri update|cargo update' "$INSTALLER"
rg -n 'Expand-SgVerifiedZip|MaxEntries|MaxExpandedBytes|unsafe entry|ReparsePoint|Is64BitOperatingSystem' "$INSTALLER" "$MOBILE_MODULE"
rg -n 'Resolve-SgExistingJdk17|Resolve-SgExistingAndroidSdk|Set-SgResolvedToolProcessEnvironment|installer and its children only|without persistent environment or PATH changes' "$INSTALLER" "$MOBILE_MODULE"
rg -n 'rejected unsafe NUL/CR/LF|sg-transport-|Start-SgEncodedProcess' "$MOBILE_MODULE"
! rg -n 'Read-Host' "$INSTALLER"
rg -n 'Read-SgInstallerChoice|Read-SgInstallerConsent|New-SgInstallerConsoleEventSink|Invoke-SgInstallerOperation' "$INSTALLER" "$INSTALLER_CONSOLE_MODULE" "$INSTALLER_ENGINE_MODULE"
rg -n 'Accept the Android SDK terms.*\[y/N\]|Install the Android emulator and create ShipGlows_API_36 now\? \[y/N\]|Install the missing Windows IDE toolchains now\? \[y/N\]' "$INSTALLER"
rg -n 'Get-SgWindowsIdeInstallPlan|Get-SgAndroidStudioState|Get-SgVisualStudioCppState|Google\.AndroidStudio|Microsoft\.VisualStudio\.2022\.Community|Microsoft\.VisualStudio\.Workload\.NativeDesktop|--norestart' "$INSTALLER" "$MOBILE_MODULE"
! rg -n 'Firebase.*(login|signin)|gcloud auth|firebase login|--includeOptional' "$INSTALLER" "$MOBILE_MODULE"
rg -n 'AccelerationWarning|hardware acceleration is not proven|Invoke-SgInteractiveBoundedProcess \$sdkManager \$emulatorPlan\.Packages 1800|Android virtual device ready' "$INSTALLER" "$MOBILE_MODULE"
rg -n 'Get-SgAndroidEmulatorProvisionState|already installed; skipping the emulator question|Repair the Android emulator and ShipGlows_API_36 now\? \[y/N\]' "$INSTALLER" "$MOBILE_MODULE"
rg -n 'Android emulator installed|Android virtual device ready|Android emulator acceleration ready|flutter emulators --launch ShipGlows_API_36|hosted Android device' "$INSTALLER"
! rg -n "create','avd','--force" "$INSTALLER"
rg -n 'Preparing coding-agent CLIs and MCPs|Test-SgToolRuns.*codex|Test-SgToolRuns.*claude|Test-SgToolRuns.*opencode|Resolve-SgKiloCommand' "$INSTALLER"
rg -n '@google/gemini-cli|Get-SgGeminiMcpAddArguments|Get-SgGeminiMcpConfigState|Gemini.*MCP readiness|[.]gemini\\GEMINI[.]md' "$INSTALLER" "$MOBILE_MODULE" "$AGENT_INSTRUCTIONS_MODULE"
rg -n "'auth'|s a.*Manage CLI authentication|Authentication" "$ENTRYPOINT"
rg -n 'Get-SgAuthenticationDefinitions|Get-SgAuthenticationState|interactive-cli|project-required' "$AUTH_MODULE"
rg -F -n "foreach (\$launcherModule in @('ShipGlows.DevServer.psm1','ShipGlows.RuntimeStatus.psm1','ShipGlows.FlutterSupervisor.ps1','ShipGlows.ProjectCatalogRefresh.ps1','ShipGlows.Auth.psm1','ShipGlows.MobileToolchain.psm1','ShipGlows.BuildArtifacts.psm1','shipglows-build-artifacts.ps1','ShipGlows.McpCatalog.json','ShipGlows.ExtensionLab.js','ShipGlows.PowerShellRuntime.psm1','ShipGlows.PowerShellRuntime.json','ShipGlows.PowerShellBootstrap.ps1','shipglows.ps1'))" "$INSTALLER"
rg -n '\$windowsFiles = .*ShipGlows[.]ExtensionLab[.]js' "$BOOTSTRAP"
rg -F -n "'bin/ShipGlows.ExtensionLab.js'" "$BOOTSTRAP"
test -f "$RUNTIME_STATUS_MODULE"
rg -n 'shipglows-version\.json|ShipGlows\.RuntimeStatus\.psm1|version=\[string\]\$versionDocument\.version' "$INSTALLER"
rg -n 'versionDestination|GetFullPath\(\$versionSource\).*GetFullPath\(\$versionDestination\)' "$WINDOWS_DIR/install-devserver.ps1"
rg -F -n '# cmd-shim-target=$target' "$INSTALLER"
rg -n 'Install-SgManagedPlaywrightRuntimes|playwright-cli|Motion runtime ready|Playwright Chromium revision' "$INSTALLER" "$AUTH_MODULE"
! rg -n 'gemini.*(auth|login)|GEMINI_API_KEY|GOOGLE_API_KEY' "$INSTALLER" "$MOBILE_MODULE"
! rg -n 'foreach \(\$server in @\(\$serverDefinitions\)\)' "$INSTALLER"
! rg -n 'Install Codex CLI now\? \[y/N\]|Each agent is a separate choice' "$INSTALLER"
rg -n 'Resolve-SgCodexPermissionMode|Set-SgCodexPermissionMode|SHIPGLOWS_CODEX_PERMISSION_MODE|one-question full installer|existing permissions were kept' "$INSTALLER"
rg -n "approvalPolicy.*'never'.*'on-request'|permissionProfile.*':danger-full-access'.*':workspace'" "$INSTALLER"
rg -n 'shipglows codex autonomous|approval_policy|default_permissions|sandbox_mode|Move-SgAtomicReplace' "$INSTALLER"
! rg -n 'shipglows-backup-|Copy-Item.*ConfigPath' "$INSTALLER" "$CODEX_MCP_MODULE"
rg -n "initialAgentReady|Install-SgMissingAgentClis|codexReady.*agentReady|claudeReady.*agentReady|opencodeReady.*agentReady|kiloReady.*agentReady" "$INSTALLER"
rg -n 'no authentication is started|pnpm could not make .* npm fallback' "$INSTALLER"
! rg -n 'Install-SgOptionalAgent|AllowInstallScripts|Install .* agent.*\[y/N\]' "$INSTALLER"
! rg -n 'McpConfigured=\$false; McpVerified=\$false' "$INSTALLER"
rg -n 'Test-SgServiceCliResult|executable verification failed|Flutter/Dart executable validation failed' "$INSTALLER" "$MOBILE_MODULE"
rg -n '\[Console\]::IsInputRedirected|non-interactive installation' "$INSTALLER"
rg -n 'keep this window open|WinGet can take several minutes|\| Out-Host' "$INSTALLER"
rg -n 'function Write-SgInstallerWarning|WARNING:.*ForegroundColor Yellow|--disable-interactivity.*\| Out-Null' "$INSTALLER"
! rg -n 'Write-Warning|winget\.Source install.*\| Out-Host' "$INSTALLER"
rg -n 'Install-SgCommandWrappers|Add-SgRuntimeToUserPath|shipglows-dev\.cmd|s\.cmd|Short command installed: s' "$INSTALLER"
rg -n 'Install-SgApplicationCommandWrapper|@call "\$target" %\*|Application command installed:' "$INSTALLER"
rg -n "Install-SgApplicationCommandWrapper '(npm|npx|corepack|pnpm|codex|claude|opencode|kilo|kilocode|gemini)'" "$INSTALLER"
rg -n 'Install-SgAgentShortcut|%~dp0\$TargetName\.cmd|Agent shortcut installed:' "$INSTALLER"
rg -n "Install-SgAgentShortcut 'c' 'claude'|Install-SgAgentShortcut 'co' 'codex'|Install-SgAgentShortcut 'cor' 'codex' @\('resume'\)|Install-SgAgentShortcut 'oc' 'opencode'|Install-SgAgentShortcut 'kc' \$kiloShortcutTarget" "$INSTALLER"
rg -n 'Install-SgShellShortcut|Shell shortcut installed:' "$INSTALLER"
rg -n "Install-SgShellShortcut 're'.*ExecutionPolicy Bypass|Install-SgShellShortcut 'ch'.*Clear-History.*Get-PSReadLineOption.*HistorySavePath.*Clear-Host" "$INSTALLER"
rg -n "Install-SgShellShortcut 'n' 'nvim %\*'" "$INSTALLER"
rg -n "Install-SgShellShortcut 'gpush' 'git push %\*'|Install-SgGitPushProfileShortcut|Remove-Item Alias:gp -Force|function global:gp" "$INSTALLER"
rg -n "git add -A|git diff --cached --quiet|git commit -m \$commitMessage|chore: sync changes|git push|ValueFromRemainingArguments" "$INSTALLER"
rg -n "gp stopped because git add -A failed|gp stopped because git commit failed|gp stopped because git push failed|No changes to commit; pushing existing local commits" "$INSTALLER"
rg -n "Get-SgPersistentProfileExecutionPolicy|MachinePolicy.*UserPolicy.*CurrentUser.*LocalMachine|Bypass.*RemoteSigned.*Unrestricted|Use gpush instead" "$INSTALLER"
rg -n "hasManagedBlock|IsMatch\(\$existing, \$managedPattern\)|outside ShipGlows's managed profile block" "$INSTALLER"
rg -n "short command.*already used|ShipGlows did not replace it" "$INSTALLER"
rg -n 'Disable-SgBlockedPowerShellShim|ChangeExtension\(\$cmdPath, .ps1.\)|shipglows-disabled|Move-Item -LiteralPath \$ps1Path' "$INSTALLER"
rg -n 'userRoot.*USERPROFILE|StartsWith\(\$userRoot.*OrdinalIgnoreCase|Protected system PowerShell shim left unchanged' "$INSTALLER"
rg -n "Disable-SgBlockedPowerShellShim '(npm|npx|corepack|pnpm|codex|claude|opencode|kilocode|gemini)'" "$INSTALLER"
last_wrapper_line="$(rg -n "Install-SgApplicationCommandWrapper 'gemini'" "$INSTALLER" | tail -1 | cut -d: -f1)"
runtime_priority_line="$(rg -n '^Add-SgRuntimeToUserPath\r?$' "$INSTALLER" | tail -1 | cut -d: -f1)"
test -n "$last_wrapper_line" && test -n "$runtime_priority_line" && test "$last_wrapper_line" -lt "$runtime_priority_line"
rg -n '_SHIPGLOWS_PWSH=%USERPROFILE%.*7\.6\.5.*pwsh\.exe|SHIPGLOWS_MANAGED_PWSH=%_SHIPGLOWS_PWSH%|shipglows-devserver\.ps1|:shipglows_bootstrap|ExecutionPolicy Bypass -File "%~dp0ShipGlows\.PowerShellBootstrap\.ps1" %\*' "$INSTALLER"
rg -n 'Remove-SgObsoleteProfileCommand|Removed the obsolete ShipGlows profile command|ShipGlows DevServer \(managed\)' "$INSTALLER"
! rg -n 'function shipglows-dev \{ & ' "$INSTALLER"
rg -n 'gh auth login --hostname github\.com --git-protocol https --web|gh auth setup-git|gh api --paginate.*user/repos.*organization_member|gh repo clone \$repository\.url \$temporaryDestination' "$ENTRYPOINT"
rg -n '\.shipglows-clone-|Move-Item -LiteralPath \$temporaryDestination -Destination \$destination|Remove-Item -LiteralPath \$temporaryDestination -Recurse -Force' "$ENTRYPOINT"
rg -n 'function Register-SgClonedProject|Clone completed but project preparation failed|Register-SgClonedProject \$destination' "$ENTRYPOINT"
! rg -n 'Clone completed but was not registered' "$ENTRYPOINT"
rg -n 'function Read-SgNodePackage|function Get-SgNodeDependencyNames|function Get-SgNodeScript|ConvertFrom-Json -ErrorAction Stop' "$MODULE"
rg -n 'function Sync-SgRegisteredProjectEnvironments|Register-SgProject \$Config \$root|Sync-SgRegisteredProjectEnvironments \$config' "$MODULE" "$INSTALLER"
rg -n '\$jsonLines = @\(|\$repositories = @\(\$jsonLines.*ConvertFrom-Json|one compact JSON object per line' "$ENTRYPOINT"
! rg -n 'gh auth token|GH_TOKEN|GITHUB_TOKEN' "$ENTRYPOINT" "$INSTALLER"
! rg -n 'WSL est disponible|Lancement de la configuration locale Windows|Utilise ensuite|Pour les projets locaux|WSL is detected' "$BOOTSTRAP"
rg -n 'The WSL launcher is present, but its runtime and distributions were not probed; this installer will continue in native Windows' "$BOOTSTRAP"
! rg -n '& wsl[.]exe' "$BOOTSTRAP"
rg -n 'does not clone the ShipGlows contributor source repository' "$BOOTSTRAP"
! rg -n "ValidateSet\\('local','full'\\)" "$BOOTSTRAP"
! rg -n 'InstallMode = \$\(if \(\$env:SHIPGLOWS_INSTALL_MODE' "$BOOTSTRAP"
rg -n '\[string\]\$InstallMode,|InstallMode must be local or full|\$InstallMode -notin @\(' "$BOOTSTRAP"
rg -n 'Select-WindowsInstallMode|Choose 1, 2, or 3|Local DevServer \(full, recommended\)|maintainer workstation|IsInputRedirected' "$BOOTSTRAP"
rg -n "USERPROFILE '.shipglows'.*'runtime'|FileAttributes.*Hidden|defaultRuntimeRoot" "$BOOTSTRAP" "$INSTALLER"
rg -n "runtimeDir = Join-Path \$ShipglowsDir 'bin'|Remove-SgLegacyRuntime|@\('bin', 'cli', 'local'\)|legacyBin" "$INSTALLER"
rg -n 'function Install-SgDefaultPython|python install --default|import ssl, sqlite3|Python manager:|Python commands:' "$INSTALLER"
rg -n 'Playwright Chromium installed:|Playwright MCP configured:|Playwright MCP verified:|Playwright MCP config:|Playwright Chromium path:' "$INSTALLER"
rg -n "ShipGlows requires uv to provide a functional default Python runtime" "$INSTALLER"
rg -n 'deferred/searchable catalog|before declaring a configured tool unavailable' "$INSTALLER"
legacy_cleanup_line="$(rg -n '^Remove-SgLegacyRuntime\r?$' "$INSTALLER" | tail -1 | cut -d: -f1)"
wrapper_install_line="$(rg -n '^Install-SgCommandWrappers\r?$' "$INSTALLER" | tail -1 | cut -d: -f1)"
test -n "$legacy_cleanup_line" && test -n "$wrapper_install_line" && test "$legacy_cleanup_line" -lt "$wrapper_install_line"
rg -n "USERPROFILE 'ShipGlows'" "$INSTALLER" "$MODULE"
! rg -n "Choose 1 or 2 \\[2\\]|'' \\{ return 'full' \\}" "$BOOTSTRAP"
rg -n "'' \{ Write-Warn 'A choice is required\. Enter 1, 2, 3, or 0\.' \}" "$BOOTSTRAP"
for windows_file in 'ShipGlows\.DevServer\.psm1' 'ShipGlows\.RuntimeStatus\.psm1' 'ShipGlows\.FlutterSupervisor\.ps1' 'ShipGlows\.ProjectCatalogRefresh\.ps1' 'ShipGlows\.CodexMcp\.psm1' 'ShipGlows\.MobileToolchain\.psm1' 'ShipGlows\.BuildArtifacts\.psm1' 'shipglows-build-artifacts\.ps1' 'ShipGlows\.McpCatalog\.json' 'ShipGlows\.InstallerEngine\.psm1' 'ShipGlows\.InstallerConsole\.psm1' 'ShipGlows\.AgentInstructions\.psm1' 'ShipGlows\.Auth\.psm1' 'ShipGlows\.DeveloperCorpus\.psm1' 'ShipGlows\.PowerShellRuntime\.psm1' 'ShipGlows\.PowerShellRuntime\.json' 'ShipGlows\.PowerShellBootstrap\.ps1' 'ShipGlows\.WslTurso\.psm1' 'shipglows-environment-provider\.ps1' 'shipglows-devserver\.ps1' 'shipglows\.ps1' 'install-devserver\.ps1'; do
  rg -n "$windows_file" "$BOOTSTRAP"
done
rg -F -n 'ShipGlows.ExtensionLab.js' "$BOOTSTRAP"
rg -F -n 'ShipGlows\.DevServer\.psm1|ShipGlows\.RuntimeStatus\.psm1|ShipGlows\.FlutterSupervisor\.ps1|ShipGlows\.ProjectCatalogRefresh\.ps1|ShipGlows\.CodexMcp\.psm1|ShipGlows\.MobileToolchain\.psm1|ShipGlows\.BuildArtifacts\.psm1|shipglows-build-artifacts\.ps1|ShipGlows\.McpCatalog\.json|ShipGlows\.InstallerEngine\.psm1|ShipGlows\.InstallerConsole\.psm1|ShipGlows\.AgentInstructions\.psm1|ShipGlows\.Auth\.psm1|ShipGlows\.DeveloperCorpus\.psm1|ShipGlows\.ExtensionLab\.js|ShipGlows\.PowerShellRuntime\.psm1|ShipGlows\.PowerShellRuntime\.json|ShipGlows\.PowerShellBootstrap\.ps1|ShipGlows\.WslTurso\.psm1|shipglows-environment-provider\.ps1|shipglows-devserver\.ps1|shipglows\.ps1|install-devserver\.ps1' "$BOOTSTRAP"
rg -n 'cli/install-turso-cloud\\?\.sh|cli/install-turso-cloud\.sh' "$BOOTSTRAP"
rg -n '\$entries\.Count -ne 35|shipglows-version\.json' "$BOOTSTRAP"
rg -n 'InstallSurface.*corpus|SHIPGLOWS_INSTALL_COMPONENTS|Install-SgDeveloperCheckout|Enable-SgWindowsDeveloperChannel' "$BOOTSTRAP"
rg -n '\$windowsCandidates = @\(' "$BOOTSTRAP"
rg -n '\$environmentCandidates = @\(|Assert-EnvironmentPackage|preparation\.py|cli/environment/.*shipglows_environment' "$BOOTSTRAP"
rg -n "Assert-SgEnvironmentPythonPackage|preparation\.py" "$INSTALLER"
rg -n 'cli/private_data\.py|private-data control-plane|privateDataSource' "$BOOTSTRAP" "$INSTALLER"
rg -n "private-data.*(status|connect|migrate|open)|privateDataCommandIndex|privateDataCandidates|private_data\.py" "$ENTRYPOINT"
! rg -n '\$windowsCandidates = @\([^)]*\) \| Where-Object' "$BOOTSTRAP"
rg -n "127\\.0\\.0\\.1|registry\\.json|registry\\.lock|commandSignature|startTimeUtc" "$MODULE"
rg -n "Test-SgGitUrl|embedded credentials|Only HTTPS and SSH" "$MODULE" "$ENTRYPOINT"
rg -n 'Get-SgProjectDescriptor|launchPath|No supported Windows launch target' "$MODULE"
rg -n 'serverDefinitions.*Generic.List|StackMcpDefinitions|ReadyServers|PendingServers' "$INSTALLER"
rg -n 'mcp[.]clerk[.]com/mcp|api[.]githubcopilot[.]com/mcp/readonly|Package=.clerk.|Need=.Clerk.' "$MOBILE_MODULE"
! rg -n 'clerk auth|gh auth token|GITHUB_TOKEN|CLERK_SECRET_KEY' "$INSTALLER" "$MOBILE_MODULE"
rg -F -n 'Flutter and Dart installed: $flutterInstalled' "$INSTALLER"
rg -F -n 'Android toolchain ready: $androidToolchainReady' "$INSTALLER"
rg -F -n 'Android licenses ready: $androidLicensesReady' "$INSTALLER"
rg -F -n 'Android device ready: $androidDeviceReady' "$INSTALLER"
rg -F -n 'Android next action: $androidNextAction' "$INSTALLER"
rg -F -n 'Android Studio installed: $androidStudioReady' "$INSTALLER"
rg -F -n 'Visual Studio Desktop C++ workload ready: $visualStudioCppReady' "$INSTALLER"
rg -F -n 'Flutter Windows desktop toolchain ready: $windowsDesktopReady' "$INSTALLER"
rg -F -n 'Firebase Android Device Streaming configured: $firebaseDeviceStreamingReady' "$INSTALLER"
rg -F -n 'Write-SgGlobalDevelopmentEnvironment $agentInfo $playwrightInfo $playwrightRuntime $pythonInfo $flutterReady $androidInfo $ideInfo $serviceInfo (Test-SgWindowsDeveloperMode)' "$INSTALLER"
rg -F -n 'Resolving the official Android command-line tools package and SHA-256' "$INSTALLER"
rg -F -n 'Downloading Android command-line tools $($package.Version)' "$INSTALLER"
rg -F -n 'Android command-line tools SHA-256 verified. Extracting the archive' "$INSTALLER"
rg -F -n 'Android command-line tools installed and executable validation passed' "$INSTALLER"
rg -n -- '--progress-bar.*--retry.*--retry-all-errors.*--connect-timeout.*--max-time' "$INSTALLER"
rg -n 'function Unregister-SgProject|Stop it before unregistering|without deleting its files' "$MODULE"
rg -n 'function Rotate-SgLogFile|5242880|\.previous|Rotate-SgLogFile \$logPath' "$MODULE"
rg -n 'call .*npm|call .*uv|rem \$signature' "$MODULE"
rg -n "flutter_tools[.]snapshot|'run','--machine','-d'|app[.]restart" "$FLUTTER_SUPERVISOR"
rg -n 'uv\.lock.*PathType Leaf|run --locked uvicorn|\.venv\\Scripts\\python\.exe|-m uvicorn.*rem \$signature' "$MODULE"
rg -n "ErrorActionPreference = 'Continue'|uv venv failed\.|-not \(Test-Path -LiteralPath \$python -PathType Leaf\)" "$MODULE"
rg -n 'Get-SgRuntimeSettings|SHIPGLOWS_ENV_PORT|SHIPGLOWS_AUTO_REPAIR|Reusing persistent port' "$MODULE"
rg -n 'launchEnvironment.*PORT|ASTRO_DEV_BACKGROUND' "$MODULE"
rg -n 'function Find-SgWorkspaceProjectCandidates|function Get-SgWorkspaceProjectCandidates|function Get-SgProjectCatalog|ProjectIndexPath|scannerVersion|generatedAt' "$MODULE"
! rg -n 'function Get-SgWorkspaceProjectCandidates|function Get-SgCandidateProjects|Get-SgProjectDescriptors' "$ENTRYPOINT"
rg -n 'IdentityByLabel|Resolve-SgProjectCatalogEntry|Get-SelectedProject .navigate.|Get-SgProjectCatalog.*ForceRefresh' "$ENTRYPOINT"
! rg -ni 'flox|\.flox|Get-SgFloxVariables|UsesFloxManifest|InsideFloxProject' "$MODULE" "$ENTRYPOINT"
rg -n 'function Show-SgWindowsDashboard|No projects discovered in the ShipGlows workspace|Show-SgWindowsDashboard' "$ENTRYPOINT"
rg -n "backOption = '0  Back to menu'|\[0\] Back to menu|if \(\$selected -eq \$backOption\)|if \(\$choice -eq '0'\)" "$ENTRYPOINT"
rg -n "'0  Quit ShipGlows'|0\) Quit ShipGlows|s x      Quit ShipGlows" "$ENTRYPOINT"
rg -n "'n  Navigate to a project'|n\) Navigate" "$ENTRYPOINT"
rg -n "'n' \{ Invoke-Navigate \}" "$ENTRYPOINT"

echo "Windows DevServer static contract: OK"
